### ISSUE TITLE
Make libmagic an optional dependency

### ISSUE THREAD

**Issue by szliu-a** [jeanralphaviles/comment_parser#21]
I use `extract_comments_from_str` only, and I know the mimetype and supply it always. However it's still complaining about "failed to find libmagic".

Can you make it only to import and call libmagic if it's actually needed?

**Comment by jeanralphaviles** [comment]
Sure thing, I've implemented this.

```python
>>> from comment_parser import comment_parser
>>> comment_parser.extract_comments('foo.c', mime='text/x-c')
[Comment( Prints Hello World, 4, False)]
>>> comment_parser.extract_comments('foo.c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jraviles/projects/src/comment_parser/comment_parser/comment_parser.py", line 78, in extract_comments
    return extract_comments_from_str(code.read(), mime)
  File "/home/jraviles/projects/src/comment_parser/comment_parser/comment_parser.py", line 97, in extract_comments_from_str
    raise ImportError('python-magic was not imported')
ImportError: python-magic was not imported
```
