### ISSUE TITLE
Cannot handle the strings containing "/*". 

### ISSUE THREAD

**Issue by boyang9602** [jeanralphaviles/comment_parser#22]
Hi I met
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 99, in extract_comments_from_str
    return parser.extract_comments(code)
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/parsers/c_parser.py", line 66, in extract_comments
    raise common.UnterminatedCommentError()
comment_parser.parsers.common.UnterminatedCommentError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 74, in extract_comments
    return extract_comments_from_str(code.read(), mime)
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 101, in extract_comments_from_str
    raise ParseError(str(e))
comment_parser.comment_parser.ParseError

```
After a simple analysis and testing, I found it is caused by the "/*" in this statement
```
        assertEquals("{\"Version\":\"2008-10-17\",\"Id\":\"Policy4324355464\",\"Statement\":[{\"Sid\":\"Stmt456464646477\",\"Action\":[\"s3:GetObject\"],\"Effect\":\"Allow\",\"Resource\":"
                + "[\"arn:aws:s3:::mybucket/some/path/*\"],\"Principal\":{\"AWS\":[\"*\"]}}]}", endpoint.getConfiguration().getPolicy());
```

**Comment by jeanralphaviles** [comment]
You didn't tell me which language this was, I assumed Java because it's the `c_parser` and you're using string concatenation.

I created this to test:

```java
public class Main {
  public static void main(String[] args) {
    assertEquals("{\"Version\":\"2008-10-17\",\"Id\":\"Policy4324355464\",\"Statement\":[{\"Sid\":\"Stmt456464646477\",\"Action\":[\"s3:GetObject\"],\"Effect\":\"Allow\",\"Resource\":"
                              + "[\"arn:aws:s3:::mybucket/some/path/*\"],\"Principal\":{\"AWS\":[\"*\"]}}]}");
  }

  public static void assertEquals(String version) {
    System.out.println(version);
  }
}
```

And comment_parser correctly parsed no comments:

```bash
$ python3 -m comment_parser.comment_parser Main.java
<empty>
```

Can you provide simple Java file that has this bug? Thank you.

**Comment by boyang9602** [comment]
```
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import comment_parser
>>> comment_parser.comment_parser.extract_comments("./CamelTestSupport.java", mime="text/x-java-source")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'comment_parser' has no attribute 'comment_parser'
>>> from comment_parser import comment_parser
>>> s = comment_parser.extract_comments('./CamelTestSupport.java', mime="text/x-java-source")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 99, in extract_comments_from_str
    return parser.extract_comments(code)
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/parsers/c_parser.py", line 66, in extract_comments
    raise common.UnterminatedCommentError()
comment_parser.parsers.common.UnterminatedCommentError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 74, in extract_comments
    return extract_comments_from_str(code.read(), mime)
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 101, in extract_comments_from_str
    raise ParseError(str(e))
comment_parser.comment_parser.ParseError
>>> 
```
Please rename the attached file to CamelTestSupport.java (github does not support .java file format so I changed to txt

[CamelTestSupport.txt](https://github.com/jeanralphaviles/comment_parser/files/5163829/CamelTestSupport.txt)

**Comment by boyang9602** [comment]
BTW, if I do not specify the mime type to text/x-java-source specifically, it will raise an exception:
```
>>> s = comment_parser.extract_comments('./CamelTestSupport.java')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 74, in extract_comments
    return extract_comments_from_str(code.read(), mime)
  File "/usr/local/lib/python3.6/dist-packages/comment_parser/comment_parser.py", line 96, in extract_comments_from_str
    raise UnsupportedError('Unsupported MIME type %s' % mime)
comment_parser.comment_parser.UnsupportedError: Unsupported MIME type text/x-java
```

**Comment by jeanralphaviles** [comment]
Thanks for the reply. Running comment parser in cli mode doesn't trigger this issue. Here's a minimal script to reproduce it. Taking a look.

```python
#!/usr/bin/python3
from comment_parser.parsers import c_parser

x = '"\"/*\""'
c_parser.extract_comments(x)
```

```bash
./test.py
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    c_parser.extract_comments(x)
  File "/home/jraviles/projects/src/comment_parser/comment_parser/parsers/c_parser.py", line 66, in extract_comments
    raise common.UnterminatedCommentError()
comment_parser.parsers.common.UnterminatedCommentError
```

The escaped quote characters confuse it: "\\"/*\\""
